[project]
name = "insurance-ml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "marathedurvesh_683", email = "durveshmarathe683@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "jupyter>=1.1.1",
    "notebook>=7.6.3",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
]

[project.scripts]
insurance-ml = "insurance_ml:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
